#!/bin/sh

. ./secrets.sh

sed -e " \
s/{{PHNUMBER}}/$PHNUMBER/g;
s/{{ADDRESS_CITY}}/$ADDRESS_CITY/g;
s/{{CGPA_UNI}}/$CGPA_UNI/g
s/{{PERCENTAGE_XII}}/$PERCENTAGE_XII/g
s/{{PERCENTAGE_X}}/$PERCENTAGE_X/g" resume.html >result.html

wkhtmltopdf --page-size A4 --page-width 125 --page-height 199.5 --enable-local-file-access -T 0 -B 0 -L 0 -R 0 --background --user-style-sheet ./style.css --zoom 30 --images result.html resume.pdf
